filter_data = false    # If True filter the data
filter_type = 0        # 0 Bandpass, 1 lowpass, 2 highpass (used only if filter_data is True)
fmin = 0.5             # Used in bandpass and highpass (used only if filter_data is True)
fmax = 50              # Used in bandpass and lowpass (used only if filter_data is True)
filter_method = 'iir'  # Filter settings (used only if filter_data is True)

# Resampling settings
resample_data = false  # If true resample the data
resample_freq = 128    # New sampling frequency (used only if resample_data is True)

# Trial segmentation
trial_start = -1    # Time (in seconds) when the trial starts. Keep this value
trial_end = -1      # Time (in seconds) when the trial end. Keep this value

# Split in train/test/validation
seed_split = 42                        # Seed for the random function used for split the dataset. Used for reproducibility
percentage_split_train_test = -1       # For ALL the data select the percentage for training and for test. -1 means to use the original division in train and test data
percentage_split_train_validation = 0.9 # For ONLY the training data select the percentage for train and for validation

# Other
n_classes = 3       # Number of labels. For datset Zhou2016 must be 3
subjects_list = []  # List of the subjects of dataset 2a to download

# Stft settings (IGNORE)(NOT USED)
use_stft_representation = false
channels_list = ['C3', 'Cz', 'C4'] # List of channel to transform with STFT. Ignore.
normalize = 0 # If different to 0 normalize the data during the dataset creation. Ignore and kept to 0
train_trials_to_keep = [] # Boolean list with the same length of the training set, BEFORE THE DIVISION with training and validation, that indicate with trial kept for the training.
# normalization_type = 1, # 0 = no normalization, 1 = ERS normalization (NOT IMPLEMENTED)

[iir_params] # Filter settings (used only if filter_data is True and filter_method is iir)
ftype = 'cheby2'
order = 20
rs = 30 

