batch_size = 30
lr = 0.01
epochs = 10
use_scheduler = true
lr_decay_rate = 0.999
optimizer_weight_decay = 0.01
alpha = 1
beta = 1
gamma = 1
recon_loss_type = 1
edge_samples_ignored = 0
gamma_dtw = 1
device = "cuda"
epoch_to_save_model = 1
path_to_save_model = "model_weights"
use_classifier = false
measure_metrics_during_training = false
print_var = true
wandb_training = true
project_name = "hvEEGNet_zhou2016"
model_artifact_name = "hvEEGNet_zhou2016"
log_freq = 1
name_training_run = ""
notes = ""
debug = false

[train_iteration_per_subject]
1 = 0
2 = 0
3 = 2
4 = 0
