batch_size = 30
lr = 0.01
epochs = 20
use_scheduler = true
lr_decay_rate = 0.999
optimizer_weight_decay = 0.01
alpha = 1
beta = 1
gamma = 1
recon_loss_type = 1
edge_samples_ignored = 0
gamma_dtw = 1
device = "cuda"
epoch_to_save_model = 1
path_to_save_model = "model_weights"
use_classifier = false
measure_metrics_during_training = false
print_var = true
wandb_training = true
project_name = ""
model_artifact_name = "hvEEGNet_d2a"
log_freq = 1
name_training_run = "experiment_hidden_space_LoRA_1"
notes = ""
debug = false
