batch_size = 30
lr = 0.01
epochs = 10
use_scheduler = true
lr_decay_rate = 0.999
optimizer_weight_decay = 0.01
alpha = 1
beta = 1
gamma = 1
recon_loss_type = 2
edge_samples_ignored = 0
average_channels = false
gamma_dtw = 1
device = "cuda"
epoch_to_save_model = 1
path_to_save_model = "model_weights"
use_classifier = false
measure_metrics_during_training = false
print_var = true
wandb_training = true
project_name = "hvEEGNet_TUAR"
model_artifact_name = "hvEEGNet_TUAR"
log_freq = 1
name_training_run = ""
notes = ""
debug = false

[train_iteration_per_subject]
NO_NOTCH_train8 = 0
NOTCH_train8 = 0
NO_NOTCH_suffle6 = 0
NOTCH_suffle6 = 0
