batch_size = 20
lr = 0.01
epochs = 20
use_scheduler = true
lr_decay_rate = 0.999
optimizer_weight_decay = 0.01
alpha = 1
beta = 1
gamma = 1
recon_loss_type = 3
block_size = 128
edge_samples_ignored = 0
average_channels = false
gamma_dtw = 1
device = "cuda"
epoch_to_save_model = 1
path_to_save_model = "model_weights"
use_classifier = false
measure_metrics_during_training = false
print_var = true
wandb_training = true
project_name = "hvEEGNet_Ofner2017"
model_artifact_name = "hvEEGNet_Ofner2017"
log_freq = 1
name_training_run = ""
notes = ""
debug = false
soft_DTW_type = 3
train_with_test_data = true

[train_iteration_per_subject_train_data]
1 = 2
2 = 0
3 = 0
4 = 0
5 = 2
6 = 1
7 = 0
8 = 0
9 = 0
10 = 0
11 = 0
12 = 0
13 = 2
14 = 0
15 = 1

[train_iteration_per_subject_test_data]
1 = 0
2 = 0
3 = 0
4 = 0
5 = 0
6 = 0
7 = 0
8 = 0
9 = 2
10 = 0
11 = 0
12 = 0
13 = 0
14 = 0
15 = 0